### ISSUE TITLE
Automatically download clts to /data if it does not yet exist

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/FluentAI#33]
This is necessary if the user wants to generate phonetic similarity using pyclts

**Comment by WinstonLam** [comment]
![Schermafbeelding 2024-10-26 233300](https://github.com/user-attachments/assets/abf715d7-e0ab-4a87-9789-54a6f9b134dc)
This line causes errors when running locally. 
Issue: FileNotFoundError due to pyclts not finding CLTS data at 'data/clts-2.3.0'.
Solution: Modify ipa2vec.py to let pyclts handle the data path automatically.

**Comment by StephanAkkerman** [comment]
@WinstonLam Yeah that's why I created this issue, I had to manually download the last clts release: https://github.com/cldf-clts/clts/releases. I think we can easily check if it exists and otherwise download it to /data
